platform:
  - x86
  - x64

branches:
  only:
    - master

install:
  - set GOPATH=%BuildFolder%
  - echo %PATH%
  - echo %GOPATH%
  - echo %BuildFolder%
  - go env
  - go version
  - go get -v -t ./...

test_script:
  - go test -v ./...

build_script:
  - go build -v -o coduno.exe
