platform:
  - x86
  - x64

branches:
  only:
    - master

install:
  - set GOPATH=%APPVEYOR_BUILD_FOLDER%
  - go env
  - go version
  - go get -v -t ./...

test_script:
  - go env
  - go test -v ./...

build_script:
  - go env
  - go build -v -o coduno.exe
